name: big_decimal
version: 0.1.0
description: >
  A bugless implementation of BigDecimal in Dart based on Java's BigDecimal

repository: https://github.com/bugless/big-decimal
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.2
