name: big_decimal
version: 1.0.0
description: >
  BigDecimal implementation
repository: https://github.com/bugless/big_decimal
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.17.2